### ISSUE TITLE
complete migration from Wordpress

### ISSUE THREAD

**Issue by nsisodiya** [pablovila/gatsby-starter-wordpress-community#2]
the current blog is self-hosted with WordPress.
I want to migrate it to Gatsby+Makrdown. So that blog can be written using markdown.
I don't want to continue using WordPress but I need old blogs too.
It seems, this codebase, connect to wordpress and try to get all the data and then create pages. so, I think, It doesn't satisfy my purpose. Kindly help me to understand!

**Comment by pablovila** [comment]
Hi,
This is a starter to keep using WordPress. The starter helps you to bring your current posts in WordPress to GraphQL and Gatsby. But the source of information will be WordPress yet. 
If you want to use Markdown there are other starters to help you. I have never done it so, I think you should start copying your posts into Markdown files, but maybe I'm wrong.

**Comment by nsisodiya** [comment]
this plugin       : WordPress --> GraphQL --> Gatsby
desired flow:  WordPress --> Markdown                   (plugin 1) - download
                        Markdown --> GraphQL --> Gatsby  (plugin 2)

**Comment by pablovila** [comment]
Although it's a good approach to follow that flow, it was the first intention of this starter
