### ISSUE TITLE
Errors when querying WordPress fields

### ISSUE THREAD

**Issue by marko-stimac** [pablovila/gatsby-starter-wordpress-community#5]
I would like to try out the starter but I get a few errors

My steps:
```
gatsby new gatsbytest https://github.com/pablovila/gatsby-starter-wordpress-community
cd gatsbytest 
npm install
gatsby develop
npm update
gatsby develop (2nd try)
```
The errors
```
Cannot query field "featured_media" on type "wordpress__POST" (blog-list.js)
Cannot query field "wordpressWpSettings" on type "Query" (header.js)
```
I have tried changing baseUrl in gatsby-config.js to a different WP website. In thatt case I get different errors like `Cannot query field "allWordpressPage" on type "Query" `(navbar.js)
I have also tried this on two computers, it fails on both: 

1st computer
Gatsby CLI version: 2.8.14
Gatsby version: 2.15.14
Node version: v10.10.0
Npm version: 6.4.1

2nd computer
Gatsby CLI version: 2.8.14
Gatsby version: 2.15.14
Node version: v8.11.4
Npm version: 6.3.0

What could be the problem?

**Comment by pablovila** [comment]
This starter relies on `gatsy-source-wordpress`. Make sure you follow instructions of how to use (https://www.gatsbyjs.org/packages/gatsby-source-wordpress/).
I think issue could be authentication with WordPress, also take in consideration it's different settings if you host your blog or if it's hosted by wordpress.com

**Comment by marko-stimac** [comment]
Thank you, I have tried to test it with data from wordpress.com for testing, but I have finally managed to make it work for local website. I needed to install WP GraphQL and JSON Basic Authentication plugins (even now I can't find this info in official docs?), also I had to install npm package pngquant-bin manually again because some files were strangely missing in its folder and Gatsby broke when generating featured images.
